{
 "title": "my-otus-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RPS, Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{uri=~\"/api/v1/user.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}}-RPS"
    },
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{uri=~\"/api/v1/user.*\",status=~\"[^2].*\"}[$__rate_interval]))",
     "legendFormat": "{{method}}-ErrPS"
    }
   ]
  },
  {
   "title": "RPS nginx by method, status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(nginx_ingress_controller_requests[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_sum{uri=~\"/api/v1/user.*\"}[$__rate_interval])) / sum by (uri, method) (rate(http_server_requests_seconds_count{uri=~\"/api/v1/user.*\"}[$__rate_interval]))",
     "legendFormat": "50-{{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, uri, method) (rate(http_server_requests_seconds_bucket{uri=~\"/api/v1/user.*\"}[$__rate_interval])))",
     "legendFormat": "95-{{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, uri, method) (rate(http_server_requests_seconds_bucket{uri=~\"/api/v1/user.*\"}[$__rate_interval])))",
     "legendFormat": "99-{{method}}"
    },
    {
     "expr": "max by (uri, method) (http_server_requests_seconds_max{uri=~\"/api/v1/user.*\"})",
     "legendFormat": "100-{{method}}"
    }
   ]
  },
  {
   "title": "nqinx квантили",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95-{{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99-{{method}}"
    },
    {
     "expr": "histogram_quantile(1.00, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "100-{{method}}"
    }
   ]
  }
 ]
}