apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-chart.fullname" . }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  #  jobLabel: stack
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}